# Generated by Django 4.0.3 on 2022-07-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_producto_existencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('total', models.FloatField(default=0)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('clientes', models.ManyToManyField(to='tienda.producto')),
            ],
        ),
    ]
